version: '3'
services:
  go:
    image: carprks/${SERVICENAME}:${VERSION}
    env_file:
        - .env
    ports:
      - 8080:80
    links:
      - db
  db:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
